# services/chroma/Dockerfile

# ChromaDB has an official Docker image.
# We don't need to build anything complex.
# This Dockerfile is for customization/documentation purposes.

FROM chromadb/chroma:0.5.0

# ChromaDB stores data in /chroma/chroma by default.
# In Docker Compose: mount a volume here for persistence.
# In Kubernetes: mount a PersistentVolumeClaim here.
# Without persistence: all vectors are LOST when container restarts!

EXPOSE 8000
